source 'https://github.com/CocoaPods/Specs'
  
# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'megahack' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TwilioVideo
  pod 'TwilioVideo', '~> 3.2'
end
